<a href="https://colab.research.google.com/github/LizaMilovanova/CM/blob/main/%D0%9B%D0%A0_%E2%84%964_%D0%9C%D1%96%D0%BB%D0%BE%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.3
Знайти матрицю С=АВ-ВА


In [1]:
import numpy as np


A = np.array([[1, 1, 1],
              [0, 1, 1],
              [0, 0, 1]])

B = np.array([[7, 5, 3],
              [0, 7, 5],
              [0, 0, 7]])

AB = np.dot(A, B)
BA = np.dot(B, A)

C = AB - BA

print("AB =\n", AB)
print("BA =\n", BA)
print("C = AB - BA =\n", C)


AB =
 [[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]]
BA =
 [[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]]
C = AB - BA =
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


2.3
Піднести матрицю до степеню

In [2]:
import numpy as np

A = np.array([[5, 0, 0, 0],
              [0, -2, 0, 0],
              [0, 0, 3, 0],
              [0, 0, 0, 2]])

A_squared = np.linalg.matrix_power(A, 2)

print("Матриця A^2:")
print(A_squared)


Матриця A^2:
[[25  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0  4]]


3.5 Знайти добуток матриць

In [4]:
import numpy as np

vector = np.array([3, 1, -1, 5, 2])

matrix = np.array([4, 0, -2, 3, 1])

result = np.dot(vector, matrix)

print("Результат добутку:", result)

Результат добутку: 31


4.5 Обчислити визначники

In [5]:
import numpy as np

matrix = np.array([
    [1, 5, -5],
    [4, 0, 3],
    [2, -10, 3]
])

determinant = np.linalg.det(matrix)

print("Визначник матриці:", determinant)

Визначник матриці: 200.0000000000001


5.3. Обчислити визначники


In [6]:
import numpy as np

matrix = np.array([
    [1, 2, 0, 0, 0],
    [1, 0, 2, 0, 0],
    [1, 0, 0, 2, 0],
    [1, 0, 0, 0, 2],
    [0, 0, 1, 1, 1]
])

determinant = np.linalg.det(matrix)

print("Визначник матриці:", determinant)

Визначник матриці: -23.999999999999993


6.5. Знайти обернену матрицю до матриці

In [7]:
import numpy as np

matrix = np.array([
    [1, 1, 1, 1],
    [1, 1, -1, -1],
    [1, -1, 1, -1],
    [1, -1, -1, 1]
])

inverse_matrix = np.linalg.inv(matrix)

print("Обернена матриця:")
print(inverse_matrix)

Обернена матриця:
[[ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25 -0.25 -0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [ 0.25 -0.25 -0.25  0.25]]


7.3. Визначити ранг матриці

In [8]:
import numpy as np

matrix = np.array([
    [-2, 3, 1, -1],
    [3, 2, 1, 4],
    [1, 2, 3, 4],
    [0, 2, 3, 3]
])

rank = np.linalg.matrix_rank(matrix)

print("Ранг матриці:", rank)

Ранг матриці: 3


8.15. Розв'язати систему лінійних рівнянь методом Крамера, матричним методом (тобто обчислити обернену матрицю) і м. Гауса. Потім зробити перевірку за допомогою solve() пакету linalg

In [10]:
import numpy as np

A = np.array([
    [1, -2, 1],
    [2, -1, 1],
    [3, 2, 2]
])

b = np.array([4, 3, 2])

def cramer_solve(A, b):
    det_A = np.linalg.det(A)
    if det_A == 0:
        raise ValueError("Система не має єдиного розв'язку")

    n = A.shape[0]
    x = np.zeros(n)
    for i in range(n):
        Ai = A.copy()
        Ai[:, i] = b
        x[i] = np.linalg.det(Ai) / det_A
    return x

x_cramer = cramer_solve(A, b)
print("Розв'язок методом Крамера:", x_cramer)

A_inv = np.linalg.inv(A)
x_matrix = np.dot(A_inv, b)
print("Розв'язок матричним методом:", x_matrix)

def gauss_solve(A, b):
    Ab = np.hstack([A, b.reshape(-1, 1)])
    n = len(b)

    for i in range(n):
        max_row = np.argmax(np.abs(Ab[i:, i])) + i

        Ab[[i, max_row]] = Ab[[max_row, i]]

        Ab[i] = Ab[i] / Ab[i, i]

        for j in range(i + 1, n):
            Ab[j] -= Ab[i] * Ab[j, i]

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = Ab[i, -1] - np.dot(Ab[i, i+1:n], x[i+1:n])
    return x

x_gauss = gauss_solve(A, b)
print("Розв'язок методом Гауса:", x_gauss)

x_solve = np.linalg.solve(A, b)
print("Розв'язок за допомогою solve():", x_solve)

Розв'язок методом Крамера: [ 0. -1.  2.]
Розв'язок матричним методом: [-2.22044605e-16 -1.00000000e+00  2.00000000e+00]
Розв'язок методом Гауса: [ 0. -2.  1.]
Розв'язок за допомогою solve(): [ 4.4408921e-16 -1.0000000e+00  2.0000000e+00]


#2
Створіть прямокутну матрицю А, яка має N рядків і М стовпців з випадковими елементами. Визначте середні значення для всіх рядків і стовпців матриці. кодом в гугл колаб

In [9]:
import numpy as np

N = 5
M = 4

A = np.random.rand(N, M)

row_means = np.mean(A, axis=1)

column_means = np.mean(A, axis=0)

print("Матриця A:")
print(A)

print("\nСередні значення для кожного рядка:")
print(row_means)

print("\nСередні значення для кожного стовпця:")
print(column_means)


Матриця A:
[[0.74618031 0.58570027 0.1444695  0.40930414]
 [0.96703172 0.31402906 0.22032243 0.91272388]
 [0.59906403 0.43779962 0.7270911  0.95667122]
 [0.92698632 0.37979976 0.53550226 0.08960482]
 [0.42382704 0.64581809 0.50196867 0.47954126]]

Середні значення для кожного рядка:
[0.47141356 0.60352677 0.68015649 0.48297329 0.51278877]

Середні значення для кожного стовпця:
[0.73261788 0.47262936 0.42587079 0.56956906]
